name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - pre-commit
  - ipykernel
  - ipython
  - setuptools
  - sphinx>=5.0
  - sphinx-book-theme >= 0.3.0
  - myst-parser
  - numpydoc
  # this project's dependencies
  - numpy
  - pandas
  - scipy
